### ISSUE TITLE
INFOGRAFIA

### ISSUE THREAD

**Issue by Sandra631** [SistemasTecTlaxiaco/infografia-de-calidad-tecnopower#1]
[Infografia.pdf](https://github.com/SistemasTecTlaxiaco/infografia-de-calidad-tecnopower/files/8777046/Infografia.pdf)

**Comment by Rmz-Rigo** [comment]
CALIFICACION:20/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
