### ISSUE TITLE
Infografía de calidad de software

### ISSUE THREAD

**Issue by Abraham890** [SistemasTecTlaxiaco/infografia-de-calidad-tecnopower#2]
[Infografía_Abraham_Reyes_Ortiz_6US.pdf](https://github.com/SistemasTecTlaxiaco/infografia-de-calidad-tecnopower/files/8854720/Infografia_Abraham_Reyes_Ortiz_6US.pdf)

**Comment by Rmz-Rigo** [comment]
CALIFICACIÓN: 20/20.

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
